[package]
name = "l337-redis"
version = "0.1.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>"]
edition = "2018"

[dependencies]
l337 = { path = ".." }
futures = "0.3"
tokio = "0.2"
# This should be changed to the next version of redis-rs when
# https://github.com/mitsuhiko/redis-rs/pull/232 is merged.
redis = { git = "https://github.com/Marwes/redis-rs.git", branch = "async_await_api" }
async-trait = "0.1.18"
log = "0.4"
