[package]
name = "l337-redis"
version = "0.1.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>"]
edition = "2018"

[dependencies]
l337 = { path = ".." }
futures = "0.3"
tokio = "0.2"
# This should be changed to the next version of redis-rs when a release is done.
redis = { git = "https://github.com/mitsuhiko/redis-rs.git", branch = "master" }
async-trait = "0.1.22"
log = "0.4"
